TRAIN:
  # ENABLE: False # default True
  DATASET: viratmask
  BATCH_SIZE: 64
  EVAL_PERIOD: 1 #10
  CHECKPOINT_PERIOD: 1 #10
  AUTO_RESUME: True
  MIXED_PRECISION: False
  CHECKPOINT_FILE_PATH: /home/sugar/workspace/slowfast/checkpoints/x3d_m.pyth
  # CHECKPOINT_FILE_PATH: /data/sugar/checkpoints/slowfast_work_dirs/checkpoints/checkpoint_epoch_00001.pyth
  CHECKPOINT_EPOCH_RESET: True
X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
TEST:
  ENABLE: True
  DATASET: viratmask
  BATCH_SIZE: 512 #64
  # CHECKPOINT_FILE_PATH: 'x3d_m.pyth' # 76.21% top1 30-view accuracy to download from the model zoo (optional).
  # NUM_SPATIAL_CROPS: 1
  NUM_SPATIAL_CROPS: 3
  NUM_ENSEMBLE_VIEWS: 1  # 10->1
  SAVE_RESULTS_PATH: results_val_det.pkl
DATA:
  MULTI_LABEL: True # False
  NUM_FRAMES: 8 #16
  SAMPLING_RATE: 5
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  # TEST_CROP_SIZE: 224 # use if TEST.NUM_SPATIAL_CROPS: 1
  TEST_CROP_SIZE: 256 # use if TEST.NUM_SPATIAL_CROPS: 3
  INPUT_CHANNEL_NUM: [3]
  DECODING_BACKEND: torchvision
  PATH_TO_DATA_DIR: /data/actev_data/clip_json
  PATH_PREFIX: /data/actev_data/virat_frame
  ENSEMBLE_METHOD: max  # sum
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.05 #0.1 # 1 machine
  BASE_LR_SCALE_NUM_SHARDS: True
  LR_POLICY: cosine
  MAX_EPOCH: 10 #300
  WEIGHT_DECAY: 5e-5
  WARMUP_EPOCHS: 1.0 #35.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 8 #400
  ARCH: x3d
  MODEL_NAME: X3D
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  # HEAD_ACT: sigmoid # softmax
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: True
NUM_GPUS: 4
RNG_SEED: 0
OUTPUT_DIR: /data/sugar/checkpoints/slowfast_work_dirs/linear_sample_addbg_mask_clipbox_gaussian/
LOG_MODEL_INFO: False
TENSORBOARD:
  ENABLE: True
  LOG_DIR: ''
  CLASS_NAMES_PATH: /home/sugar/workspace/slowfast/configs/Virat/tensorboard/personobject_class2id.json
  CONFUSION_MATRIX:
    ENABLE: True
    SUBSET_PATH: /home/sugar/workspace/slowfast/configs/Virat/tensorboard/personobject_classes.txt
  HISTOGRAM:
    ENABLE: True
    TOPK: 8
    SUBSET_PATH: /home/sugar/workspace/slowfast/configs/Virat/tensorboard/personobject_classes.txt
